language: julia

os:
  - linux
  - windows
  - osx

julia:
  - 1.3

notifications:
  email: false

script:
    julia --project="" -e 'using Pkg; Pkg.develop(PackageSpec(path=".")); Pkg.build("MKL"; verbose=true); Pkg.test("MKL")'

