language: julia

os:
  - linux
  - windows
  - osx

julia:
  - nightly

jobs:
  allow_failures:
  - julia: nightly

notifications:
  email: false

script:
    julia --project="" -e 'using Pkg; Pkg.add(url="git@github.com:JuliaLinearAlgebra/MKL.jl", rev="lbt"); Pkg.test("MKL")'
